import Head from 'next/head'


export default function Favorites() {
 

  return (
    <>
      <Head>
        <title>XCO+ | Favoritos </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        
      </section>
    </>
  )
}
